name: Pylint

on: [push]

jobs:
  test:
    runs-on: docker
    container:
      image: fedora:latest
#    strategy:
#      matrix:
#        python-version: ["3.8.17", "3.9.17", "3.10.12", "3.11.4"]
    steps:
    - name: Install NodeJS for actions
      run: |
        echo -e 'max_parallel_downloads=20\ndeltarpm=False\nfastestmirror=False' >> /etc/dnf/dnf.conf
        dnf -yq install nodejs
        dnf clean all
    - uses: actions/checkout@v3
#    - name: "Set up Python ${{ matrix.python-version }}"
#      uses: https://github.com/actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
