name: Pylint

on: [push]

jobs:
  test:
    runs-on: docker
    container:
      image: fedora:38  # lock to latest *stable*; rawhide/next is 'latest' tag
    steps:
    - name: Install package dependencies
      run: |
        echo "Making DNF more performant with these directives:"
        echo -e 'max_parallel_downloads=20\ndeltarpm=False\nfastestmirror=False' | tee -a /etc/dnf/dnf.conf
        dnf -yq install nodejs git python3-pip
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --no-compile -r requirements.txt
        python3 -m pip install pylint
    - name: Show Python modules / versions
      run: python3 -m pip list
    - name: Analyse the code with pylint
      run: |
        pylint $(git ls-files '*.py')
