name: Pylint

on: [push]

jobs:
  test:
    runs-on: docker
    container:
      image: fedora:38  # lock to latest *stable*; rawhide/next is 'latest' tag
#    strategy:
#      matrix:
#        python-version: ["3.8.17", "3.9.17", "3.10.12", "3.11.4"]
    steps:
    - name: Install Package-based Deps
      run: |
        echo -e 'max_parallel_downloads=20\ndeltarpm=False\nfastestmirror=False' | tee -a /etc/dnf/dnf.conf
        dnf -yq install nodejs git pylint python3-pip python3-virtualenv python3-pylint-venv
        dnf clean all
#    - name: "Set up Python ${{ matrix.python-version }}"
#      uses: https://github.com/actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
    - name: Install Python Deps
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        source venv/bin/activate
        pylint $(git ls-files '*.py')
